name: Scrape Allergy Data

on:
  push:
  workflow_dispatch:
  schedule:
    - cron:  '0 * * * *' # Every hour. Ref https://crontab.guru/examples.html

jobs:
  scheduled:
    name: Allergy Job
    runs-on: ubuntu-latest
    env:
      HTML_NAME: allergy_v3.raw.html
      JS_ARRAYS_NAME: /tmp/allergy_v3.arrays.js
      HTML_HOURLY_NAME: raw/allergy_hourly.json.html
    steps:
    - name: Checkout
      uses: actions/checkout@master

    - name: Fetch latest daily data
      run: |-
        curl https://media.psg.nexstardigital.net/kxan/weather/allergy/allergy_v5.js?v=5 > $HTML_NAME

    - name: Process daily data
      run: |-
        awk '/var ary/,/;/' $HTML_NAME > $JS_ARRAYS_NAME
      continue-on-error: true

    - name: Fetch latest hourly data
      run: |-
        curl https://media.psg.nexstardigital.net/kxan/weather/allergy/allergy_hourly.json > $HTML_HOURLY_NAME
      continue-on-error: true

    - name: Setup Node.js environment
      uses: actions/setup-node@v4.0.0
    - run: (npm install && npm run start)

    - name: Commit and push if it changed
      run: |-
        git config user.name "Automated"
        git config user.email "actions@users.noreply.github.com"
        git add -A
        timestamp=$(date +"%Y-%m-%d %T")
        git commit -m "Latest data: ${timestamp} (from: $GITHUB_EVENT_NAME)" || exit 0
        git push
