# httpsmedia.kxan.comnxs-kxantv-media-us-east-1oembedwx_embedallergyallergy_v3.5.jsv=4
name: Scrape Allergy Data

on:
  push:
  workflow_dispatch:
  schedule:
    - cron:  '0 * * * *' # Every 12 hours. Ref https://crontab.guru/examples.html

jobs:
  scheduled:
    name: Allergy Job
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@master
    - name: Fetch latest data
      run: |-
        curl https://media.kxan.com/nxs-kxantv-media-us-east-1/oembed/wx_embed/allergy/allergy_v3.5.js?v=4 > allergy_v3.raw.html
    - name: Commit and push if it changed
      run: |-
        git config user.name "Automated"
        git config user.email "actions@users.noreply.github.com"
        git add -A
        timestamp=$(date -u)
        git commit -m "Latest data: ${timestamp}" || exit 0
        git push
